package wizard

import (
	"fmt"
	"os"
	"regexp"
	"strings"

	"github.com/wrcron2/market-ai-factory/backend/internal/orchestrator"
)

// ─── Hangar 1: validate_repo ─────────────────────────────────────────────────
// Proves the source repo exists and pins the commit SHA the product will run.

type ValidateRepo struct{}

func (ValidateRepo) ID() string          { return "validate_repo" }
func (ValidateRepo) Title() string       { return "Validate source repo" }
func (ValidateRepo) NeedsInput() []string { return nil }

func (ValidateRepo) Execute(ctx *RunContext) error {
	sha, err := orchestrator.LsRemoteHead(ctx.Run.SourceRepo)
	if err != nil {
		return nil // Check() reports the reachability issue with a hint
	}
	ctx.State["source_sha"] = sha
	return nil
}

func (ValidateRepo) Check(ctx *RunContext) []Issue {
	var issues []Issue
	if !strings.HasPrefix(ctx.Run.SourceRepo, "https://") && !strings.HasPrefix(ctx.Run.SourceRepo, "git@") {
		issues = append(issues, Issue{
			Code: "bad_repo_url", Message: fmt.Sprintf("%q is not a git URL", ctx.Run.SourceRepo),
			Hint: "Use the https://github.com/owner/repo form.",
		})
		return issues
	}
	if ctx.StateStr("source_sha") == "" {
		sha, err := orchestrator.LsRemoteHead(ctx.Run.SourceRepo)
		if err != nil {
			issues = append(issues, Issue{
				Code: "repo_unreachable", Message: err.Error(),
				Hint: "Is the repo private? Make it public or configure a GITHUB_TOKEN, then Refresh.",
			})
			return issues
		}
		ctx.State["source_sha"] = sha
	}
	return issues
}

// ─── Hangar 2: create_space ──────────────────────────────────────────────────
// Allocates the port range and writes products/<name>/product.yaml.

var slugRe = regexp.MustCompile(`^[a-z0-9][a-z0-9-]{1,40}$`)

type CreateSpace struct{}

func (CreateSpace) ID() string          { return "create_space" }
func (CreateSpace) Title() string       { return "Create product space" }
func (CreateSpace) NeedsInput() []string { return nil }

func (CreateSpace) Execute(ctx *RunContext) error {
	if !slugRe.MatchString(ctx.Run.ProductName) {
		return nil // Check reports it
	}
	adopted, _ := ctx.State["adopted"].(bool)
	portBase := 0
	if existing, ok := ctx.State["port_base"].(float64); ok && existing > 0 {
		// Re-execution after Back must keep the original allocation — a
		// fresh MaxPortBase() here would silently move the product's ports
		// out from under URLs captured in later steps.
		portBase = int(existing)
	} else if !adopted {
		maxBase, err := ctx.DB.MaxPortBase()
		if err != nil {
			return fmt.Errorf("port allocation: %w", err)
		}
		portBase = maxBase + 100
		if portBase < 10100 {
			portBase = 10100
		}
	}
	ctx.State["port_base"] = portBase

	dir := ctx.RepoRoot + "/products/" + ctx.Run.ProductName
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	yaml := fmt.Sprintf(`# Generated by the Add wizard — edit knowingly.
name: %s
source_repo: %s
source_sha: %s
adopted: %v
port_base: %d
# Filled by later hangars:
#   budget_usd     (set_budget)
#   dashboard_url / health_url (deploy / verify_health)
`, ctx.Run.ProductName, ctx.Run.SourceRepo, ctx.StateStr("source_sha"), adopted, portBase)
	return os.WriteFile(dir+"/product.yaml", []byte(yaml), 0o644)
}

func (CreateSpace) Check(ctx *RunContext) []Issue {
	var issues []Issue
	if !slugRe.MatchString(ctx.Run.ProductName) {
		issues = append(issues, Issue{
			Code: "bad_slug", Message: fmt.Sprintf("%q is not a valid product name", ctx.Run.ProductName),
			Hint: "Lowercase letters, digits, dashes; 2–41 chars.",
		})
	}
	if existing, err := ctx.DB.GetProduct(ctx.Run.ProductName); err == nil && existing != nil {
		issues = append(issues, Issue{
			Code: "name_taken", Message: fmt.Sprintf("a product named %q already exists", ctx.Run.ProductName),
		})
	}
	if _, err := os.Stat(ctx.RepoRoot + "/products/" + ctx.Run.ProductName + "/product.yaml"); err != nil {
		issues = append(issues, Issue{Code: "spec_missing", Message: "product.yaml not written yet"})
	}
	return issues
}
